version: "3.6"
services:
  database:
    image: mongo:4.4.1-bionic
    container_name: vention_machine_cloud_test-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=vention_machine_cloud_test
      - MONGO_INITDB_ROOT_USERNAME=vention_machine_cloud_test
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
